[package]
name = "bevy_arangodb"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.16.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
arangors = "0.6.0"
tokio = { version = "1.45.1", features = [
  "rt-multi-thread",
  "macros",
  "time",
  "net",
] }
mockall = "0.13.1"
futures = "0.3.31"
