//! Test doubles for [`super::connection::DatabaseConnection`].
//!
//! Only compiled with the `mock` feature or in unit tests. `MockDatabaseConnection`
//! is generated by `mockall` on the trait in [`super::connection`].

pub use super::connection::MockDatabaseConnection;
